### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by MendyBerger** [HeroicKatora/static-alloc#74]
I have the following code that's using `Bump`.
As you can see there's only one single allocation, that allocation should be cleared right after that scope closes, but my `alloc_error_handler` is being called after running for a short period of time. Any idea why this could be happening? Am I missing something here?

```rust
#![no_std]
#![feature(alloc_error_handler)]

use alloc::string::ToString;
use static_alloc::Bump;

// initialize allocator
extern crate alloc;
#[global_allocator]
static A: Bump<[u8; 1 << 16]> = Bump::uninit();

// import function for printing
#[link(wasm_import_module = "arduino")]
extern {
    fn log_char(c: u8);
}
pub fn println(message: &str) {
    message.as_bytes().iter().for_each(|c| {
        unsafe { log_char(*c) };
    });

    unsafe { log_char('\n' as u8) };
}

// main function
#[no_mangle]
pub extern fn _start() {
    let mut i = u32::MAX;
    loop {
        i -= 1;
        // only allocation, should be cleaned up at end of loop
        let i_string = i.to_string();
        println(&i_string);
    }
}

// error handlers
#[panic_handler]
pub fn panic(_: &::core::panic::PanicInfo) -> ! {
    println("panic");
    core::arch::wasm32::unreachable();
}
#[alloc_error_handler]
pub fn oom(_: ::core::alloc::Layout) -> ! {
    println("out of memory");
    core::arch::wasm32::unreachable();
}
```

Full example [here](https://github.com/MendyBerger/bump-oom)

**Comment by HeroicKatora** [comment]
Works as specified. `Bump` does *not* deallocate anything, ever. You can combine it with [`linked-list-allocator`](https://docs.rs/linked_list_allocator/latest/linked_list_allocator/) for a deterministic and local allocator *with* cleanup.

**Comment by MendyBerger** [comment]
@HeroicKatora can I open a PR that adds a warning in to the RAEDME about this limitation, and add a links to `linked-list-allocato`r?

**Comment by HeroicKatora** [comment]
Of course, if you feel there's additional information missing. The only thing I'd ask in advance is that it should include a mention of [`reset`](https://docs.rs/static-alloc/latest/static_alloc/bump/struct.Bump.html#method.reset)—it's not possible to use on a global instance though.
